"""
hazard_db.py — 本地化学品危险品数据库（GHS 分类内置库）

数据来源：GHS 联合国全球化学品统一分类和标签制度（第9修订版）
覆盖约 200 种最常见实验室化学品，用于网络不可用时的离线回退。

每条记录格式：
{
    "aliases": [别名列表，小写，用于模糊匹配],
    "cn_name": "中文名",
    "hazards": ["危害描述列表"],
    "ghs_codes": ["H编码列表"],
    "signal_word": "Danger" | "Warning" | "None",
    "pictograms": ["GHS图标代码"],
    "high_risk": True/False  # 是否属于高危物质
}
"""

from __future__ import annotations
import re

# ─────────────────────────────────────────────────────────────────────────────
# 本地数据库主体
# ─────────────────────────────────────────────────────────────────────────────
LOCAL_HAZARD_DB: list[dict] = [
    # ── 强酸 ──────────────────────────────────────────────────────────────
    {
        "aliases": ["sulfuric acid", "sulphuric acid", "h2so4"],
        "cn_name": "硫酸",
        "hazards": ["Causes severe skin burns and eye damage", "Harmful if swallowed",
                    "May be corrosive to metals"],
        "ghs_codes": ["H290", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS05"],
        "high_risk": True,
    },
    {
        "aliases": ["hydrochloric acid", "hcl", "muriatic acid"],
        "cn_name": "盐酸",
        "hazards": ["Causes severe skin burns and eye damage",
                    "May cause respiratory irritation"],
        "ghs_codes": ["H314", "H335"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS07"],
        "high_risk": True,
    },
    {
        "aliases": ["nitric acid", "hno3"],
        "cn_name": "硝酸",
        "hazards": ["Causes severe skin burns and eye damage",
                    "May intensify fire; oxidizer"],
        "ghs_codes": ["H272", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS05"],
        "high_risk": True,
    },
    {
        "aliases": ["phosphoric acid", "h3po4", "orthophosphoric acid"],
        "cn_name": "磷酸",
        "hazards": ["Causes skin irritation", "Causes serious eye damage"],
        "ghs_codes": ["H315", "H318"],
        "signal_word": "Warning",
        "pictograms": ["GHS05"],
        "high_risk": False,
    },
    {
        "aliases": ["hydrofluoric acid", "hf", "fluorhydric acid"],
        "cn_name": "氢氟酸",
        "hazards": ["Fatal in contact with skin", "Fatal if inhaled",
                    "Causes severe skin burns and eye damage",
                    "Toxic to aquatic life with long lasting effects"],
        "ghs_codes": ["H300", "H310", "H314", "H330", "H411"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS06", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["acetic acid", "ethanoic acid", "ch3cooh"],
        "cn_name": "乙酸/醋酸",
        "hazards": ["Flammable liquid and vapour", "Causes skin burns",
                    "Causes serious eye damage"],
        "ghs_codes": ["H226", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05"],
        "high_risk": False,
    },
    # ── 强碱 ──────────────────────────────────────────────────────────────
    {
        "aliases": ["sodium hydroxide", "naoh", "caustic soda", "lye"],
        "cn_name": "氢氧化钠",
        "hazards": ["Causes severe skin burns and eye damage",
                    "May be corrosive to metals"],
        "ghs_codes": ["H290", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS05"],
        "high_risk": True,
    },
    {
        "aliases": ["potassium hydroxide", "koh", "caustic potash"],
        "cn_name": "氢氧化钾",
        "hazards": ["Causes severe skin burns and eye damage",
                    "May be corrosive to metals"],
        "ghs_codes": ["H290", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS05"],
        "high_risk": True,
    },
    {
        "aliases": ["ammonia", "nh3", "ammonium hydroxide"],
        "cn_name": "氨/氨水",
        "hazards": ["Flammable gas", "Toxic if inhaled",
                    "Causes severe skin burns and eye damage",
                    "Toxic to aquatic life with long lasting effects"],
        "ghs_codes": ["H221", "H280", "H314", "H331", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS06", "GHS09"],
        "high_risk": True,
    },
    # ── 有机溶剂 ─────────────────────────────────────────────────────────
    {
        "aliases": ["ethanol", "ethyl alcohol", "alcohol", "etoh"],
        "cn_name": "乙醇",
        "hazards": ["Flammable liquid and vapour",
                    "May cause drowsiness or dizziness"],
        "ghs_codes": ["H225", "H336"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["methanol", "methyl alcohol", "wood alcohol", "meoh"],
        "cn_name": "甲醇",
        "hazards": ["Highly flammable liquid and vapour",
                    "Toxic if swallowed", "Toxic in contact with skin",
                    "Toxic if inhaled"],
        "ghs_codes": ["H225", "H301", "H311", "H331"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS06"],
        "high_risk": True,
    },
    {
        "aliases": ["acetone", "2-propanone", "dimethyl ketone"],
        "cn_name": "丙酮",
        "hazards": ["Highly flammable liquid and vapour",
                    "May cause drowsiness or dizziness"],
        "ghs_codes": ["H225", "H319", "H336"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["toluene", "methylbenzene", "toluol"],
        "cn_name": "甲苯",
        "hazards": ["Highly flammable liquid and vapour",
                    "May damage fertility or the unborn child",
                    "May cause drowsiness or dizziness",
                    "Toxic if inhaled"],
        "ghs_codes": ["H225", "H304", "H315", "H336", "H361d", "H373"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["benzene", "benzol"],
        "cn_name": "苯",
        "hazards": ["Highly flammable liquid and vapour",
                    "May cause genetic defects", "May cause cancer",
                    "Toxic if inhaled", "Causes damage to organs through prolonged exposure"],
        "ghs_codes": ["H225", "H304", "H315", "H319", "H340", "H350", "H372"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["dichloromethane", "methylene chloride", "dcm", "ch2cl2"],
        "cn_name": "二氯甲烷",
        "hazards": ["Suspected of causing cancer",
                    "May cause drowsiness or dizziness",
                    "Harmful if inhaled"],
        "ghs_codes": ["H315", "H319", "H335", "H351"],
        "signal_word": "Warning",
        "pictograms": ["GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["chloroform", "trichloromethane", "chcl3"],
        "cn_name": "氯仿/三氯甲烷",
        "hazards": ["Harmful if swallowed", "Harmful if inhaled",
                    "Suspected of causing cancer",
                    "May cause damage to organs through prolonged exposure"],
        "ghs_codes": ["H302", "H315", "H319", "H331", "H351", "H361", "H372"],
        "signal_word": "Warning",
        "pictograms": ["GHS06", "GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["diethyl ether", "ethyl ether", "ether", "et2o"],
        "cn_name": "乙醚",
        "hazards": ["Extremely flammable liquid and vapour",
                    "May form explosive peroxides",
                    "May cause drowsiness or dizziness"],
        "ghs_codes": ["H224", "H302", "H336"],
        "signal_word": "Danger",
        "pictograms": ["GHS01", "GHS02", "GHS07"],
        "high_risk": True,
    },
    {
        "aliases": ["hexane", "n-hexane"],
        "cn_name": "正己烷",
        "hazards": ["Extremely flammable liquid and vapour",
                    "May be fatal if swallowed and enters airways",
                    "May cause damage to organs through prolonged exposure"],
        "ghs_codes": ["H225", "H304", "H336", "H361f", "H373"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["dimethyl sulfoxide", "dmso"],
        "cn_name": "二甲基亚砜",
        "hazards": ["Causes skin irritation", "Causes eye irritation"],
        "ghs_codes": ["H315", "H319"],
        "signal_word": "Warning",
        "pictograms": ["GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["isopropanol", "isopropyl alcohol", "2-propanol", "ipa"],
        "cn_name": "异丙醇",
        "hazards": ["Highly flammable liquid and vapour",
                    "May cause drowsiness or dizziness",
                    "Causes serious eye irritation"],
        "ghs_codes": ["H225", "H319", "H336"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["n-methyl-2-pyrrolidone", "nmp", "1-methyl-2-pyrrolidone"],
        "cn_name": "N-甲基吡咯烷酮",
        "hazards": ["May damage the unborn child",
                    "Causes skin irritation", "Causes serious eye irritation",
                    "May cause respiratory irritation"],
        "ghs_codes": ["H315", "H319", "H335", "H360D"],
        "signal_word": "Danger",
        "pictograms": ["GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["tetrahydrofuran", "thf"],
        "cn_name": "四氢呋喃",
        "hazards": ["Highly flammable liquid and vapour",
                    "May form explosive peroxides",
                    "May cause drowsiness or dizziness"],
        "ghs_codes": ["H225", "H302", "H319", "H335"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["dimethylformamide", "dmf", "n,n-dimethylformamide"],
        "cn_name": "N,N-二甲基甲酰胺",
        "hazards": ["Highly flammable liquid and vapour",
                    "May damage the unborn child",
                    "Harmful if inhaled"],
        "ghs_codes": ["H226", "H312", "H319", "H332", "H360D"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["xylene", "xylol", "dimethylbenzene"],
        "cn_name": "二甲苯",
        "hazards": ["Highly flammable liquid and vapour",
                    "Harmful if swallowed", "Causes skin irritation"],
        "ghs_codes": ["H226", "H304", "H312", "H315", "H332"],
        "signal_word": "Warning",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    # ── 氧化剂 ───────────────────────────────────────────────────────────
    {
        "aliases": ["hydrogen peroxide", "h2o2"],
        "cn_name": "过氧化氢/双氧水",
        "hazards": ["May intensify fire; oxidizer",
                    "Causes severe skin burns and eye damage",
                    "Harmful if inhaled"],
        "ghs_codes": ["H271", "H302", "H314", "H332", "H335", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS05", "GHS07"],
        "high_risk": True,
    },
    {
        "aliases": ["potassium permanganate", "kmno4"],
        "cn_name": "高锰酸钾",
        "hazards": ["Oxidizing solid", "Harmful if swallowed",
                    "Causes skin burns", "Very toxic to aquatic life"],
        "ghs_codes": ["H272", "H302", "H314", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS05", "GHS07", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["sodium hypochlorite", "bleach", "naocl"],
        "cn_name": "次氯酸钠/漂白剂",
        "hazards": ["Causes severe skin burns and eye damage",
                    "Toxic to aquatic life with long lasting effects",
                    "Harmful if inhaled"],
        "ghs_codes": ["H290", "H314", "H335", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS07", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["potassium dichromate", "k2cr2o7"],
        "cn_name": "重铬酸钾",
        "hazards": ["Oxidizing solid", "Causes severe skin burns and eye damage",
                    "Fatal if inhaled", "May cause cancer",
                    "May cause genetic defects", "Toxic to aquatic life"],
        "ghs_codes": ["H272", "H301", "H312", "H314", "H317", "H330",
                      "H334", "H340", "H350", "H360FD", "H372", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS01", "GHS03", "GHS05", "GHS06", "GHS08", "GHS09"],
        "high_risk": True,
    },
    # ── 重金属盐 & 无机物 ─────────────────────────────────────────────────
    {
        "aliases": ["lead nitrate", "pb(no3)2", "lead(ii) nitrate"],
        "cn_name": "硝酸铅",
        "hazards": ["Oxidizing solid", "Harmful if swallowed",
                    "Suspected of damaging the unborn child",
                    "Toxic to aquatic life"],
        "ghs_codes": ["H272", "H302", "H360Df", "H373", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS07", "GHS08", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["mercury chloride", "hgcl2", "mercuric chloride"],
        "cn_name": "氯化汞",
        "hazards": ["Fatal if swallowed", "Fatal in contact with skin",
                    "Fatal if inhaled", "May cause genetic defects",
                    "Very toxic to aquatic life"],
        "ghs_codes": ["H290", "H300", "H310", "H330", "H340", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS06", "GHS08", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["sodium cyanide", "nacn"],
        "cn_name": "氰化钠",
        "hazards": ["Fatal if swallowed", "Fatal in contact with skin",
                    "Fatal if inhaled", "Very toxic to aquatic life"],
        "ghs_codes": ["H290", "H300", "H310", "H330", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS06", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["arsenic trioxide", "as2o3", "arsenious acid"],
        "cn_name": "三氧化二砷/砒霜",
        "hazards": ["Fatal if swallowed", "Fatal if inhaled",
                    "May cause cancer", "Very toxic to aquatic life"],
        "ghs_codes": ["H300", "H330", "H350", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS06", "GHS08", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["copper sulfate", "cuso4", "copper(ii) sulfate", "blue vitriol"],
        "cn_name": "硫酸铜",
        "hazards": ["Harmful if swallowed", "Causes skin irritation",
                    "Very toxic to aquatic life"],
        "ghs_codes": ["H302", "H318", "H400", "H410"],
        "signal_word": "Warning",
        "pictograms": ["GHS05", "GHS07", "GHS09"],
        "high_risk": False,
    },
    {
        "aliases": ["iron(iii) chloride", "fecl3", "ferric chloride"],
        "cn_name": "三氯化铁",
        "hazards": ["Harmful if swallowed", "Causes skin irritation",
                    "Causes serious eye damage"],
        "ghs_codes": ["H302", "H318"],
        "signal_word": "Warning",
        "pictograms": ["GHS05", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["zinc chloride", "zncl2"],
        "cn_name": "氯化锌",
        "hazards": ["May be corrosive to metals", "Harmful if swallowed",
                    "Causes severe skin burns", "Very toxic to aquatic life"],
        "ghs_codes": ["H290", "H302", "H314", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS07", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["silver nitrate", "agno3"],
        "cn_name": "硝酸银",
        "hazards": ["Oxidizing solid", "Causes severe skin burns and eye damage",
                    "Harmful to aquatic life"],
        "ghs_codes": ["H272", "H290", "H314", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS05", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["ammonium nitrate", "nh4no3"],
        "cn_name": "硝酸铵",
        "hazards": ["Explosive when heated under confinement",
                    "Oxidizing solid", "Harmful if swallowed"],
        "ghs_codes": ["H201", "H270", "H302"],
        "signal_word": "Danger",
        "pictograms": ["GHS01", "GHS03", "GHS07"],
        "high_risk": True,
    },
    # ── 气体 ─────────────────────────────────────────────────────────────
    {
        "aliases": ["carbon monoxide", "co"],
        "cn_name": "一氧化碳",
        "hazards": ["Flammable gas", "Fatal if inhaled",
                    "May damage fertility or the unborn child",
                    "Causes damage to organs through prolonged exposure"],
        "ghs_codes": ["H220", "H280", "H331", "H360D", "H372"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS06", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["hydrogen sulfide", "h2s"],
        "cn_name": "硫化氢",
        "hazards": ["Extremely flammable gas", "Fatal if inhaled",
                    "Very toxic to aquatic life"],
        "ghs_codes": ["H220", "H280", "H330", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS06", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["chlorine", "cl2"],
        "cn_name": "氯气",
        "hazards": ["Oxidizing gas", "Toxic if inhaled",
                    "Causes severe skin burns and eye damage",
                    "Very toxic to aquatic life"],
        "ghs_codes": ["H270", "H280", "H314", "H331", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS05", "GHS06", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["oxygen", "o2"],
        "cn_name": "氧气",
        "hazards": ["Oxidizing gas", "Contains gas under pressure"],
        "ghs_codes": ["H270", "H280"],
        "signal_word": "Danger",
        "pictograms": ["GHS03", "GHS04"],
        "high_risk": False,
    },
    {
        "aliases": ["nitrogen", "n2"],
        "cn_name": "氮气",
        "hazards": ["Contains gas under pressure; may explode if heated",
                    "May displace oxygen and cause rapid suffocation"],
        "ghs_codes": ["H280"],
        "signal_word": "Warning",
        "pictograms": ["GHS04"],
        "high_risk": False,
    },
    {
        "aliases": ["argon", "ar"],
        "cn_name": "氩气",
        "hazards": ["Contains gas under pressure",
                    "May displace oxygen and cause rapid suffocation"],
        "ghs_codes": ["H280"],
        "signal_word": "Warning",
        "pictograms": ["GHS04"],
        "high_risk": False,
    },
    # ── 有机化学试剂 ──────────────────────────────────────────────────────
    {
        "aliases": ["formaldehyde", "methanal", "formalin", "hcho"],
        "cn_name": "甲醛",
        "hazards": ["Highly flammable liquid and vapour",
                    "Fatal if swallowed", "Fatal if inhaled",
                    "May cause cancer", "Causes skin burns",
                    "Causes serious eye damage", "May cause sensitization"],
        "ghs_codes": ["H225", "H301", "H311", "H314", "H317", "H331", "H350"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS06", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["phenol", "carbolic acid", "hydroxybenzene"],
        "cn_name": "苯酚",
        "hazards": ["Fatal if swallowed", "Fatal in contact with skin",
                    "Fatal if inhaled", "Causes severe skin burns",
                    "Toxic to aquatic life"],
        "ghs_codes": ["H290", "H301", "H311", "H314", "H331", "H341",
                      "H373", "H400", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS06", "GHS08", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["pyridine"],
        "cn_name": "吡啶",
        "hazards": ["Highly flammable liquid and vapour",
                    "Harmful if swallowed", "Harmful if inhaled",
                    "Causes skin irritation"],
        "ghs_codes": ["H225", "H302", "H312", "H315", "H319", "H332"],
        "signal_word": "Warning",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["acetonitrile", "methyl cyanide", "mecn", "ch3cn"],
        "cn_name": "乙腈",
        "hazards": ["Highly flammable liquid and vapour",
                    "Harmful if swallowed", "Harmful if inhaled"],
        "ghs_codes": ["H225", "H302", "H312", "H319", "H332"],
        "signal_word": "Warning",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["acrylamide"],
        "cn_name": "丙烯酰胺",
        "hazards": ["May cause cancer", "May cause genetic defects",
                    "Toxic if swallowed", "Toxic in contact with skin",
                    "Causes skin sensitization"],
        "ghs_codes": ["H301", "H311", "H317", "H331", "H340", "H350",
                      "H372", "H410"],
        "signal_word": "Danger",
        "pictograms": ["GHS06", "GHS07", "GHS08", "GHS09"],
        "high_risk": True,
    },
    {
        "aliases": ["ethylene glycol", "monoethylene glycol", "meg"],
        "cn_name": "乙二醇",
        "hazards": ["Harmful if swallowed",
                    "May cause damage to organs through prolonged exposure"],
        "ghs_codes": ["H302", "H373"],
        "signal_word": "Warning",
        "pictograms": ["GHS07", "GHS08"],
        "high_risk": False,
    },
    {
        "aliases": ["glycerol", "glycerin", "glycerine"],
        "cn_name": "甘油",
        "hazards": [],
        "ghs_codes": [],
        "signal_word": "None",
        "pictograms": [],
        "high_risk": False,
    },
    {
        "aliases": ["sodium dodecyl sulfate", "sds", "sodium lauryl sulfate", "sls"],
        "cn_name": "十二烷基硫酸钠",
        "hazards": ["Causes skin irritation", "Causes serious eye damage",
                    "May cause respiratory irritation"],
        "ghs_codes": ["H315", "H318", "H335"],
        "signal_word": "Danger",
        "pictograms": ["GHS05", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["triethylamine", "tea", "n,n-diethylethanamine"],
        "cn_name": "三乙胺",
        "hazards": ["Highly flammable liquid and vapour",
                    "Harmful if inhaled", "Causes severe skin burns"],
        "ghs_codes": ["H225", "H302", "H312", "H314", "H332"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS07"],
        "high_risk": True,
    },
    # ── 催化剂 & 特殊试剂 ─────────────────────────────────────────────────
    {
        "aliases": ["palladium", "pd", "palladium catalyst", "pd/c"],
        "cn_name": "钯/钯碳催化剂",
        "hazards": ["Flammable solid", "Causes skin sensitization"],
        "ghs_codes": ["H228", "H317"],
        "signal_word": "Warning",
        "pictograms": ["GHS02", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["n-butyllithium", "n-buli", "butyllithium"],
        "cn_name": "正丁基锂",
        "hazards": ["Spontaneously flammable in air",
                    "Reacts violently with water",
                    "Causes severe skin burns"],
        "ghs_codes": ["H250", "H260", "H314"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05"],
        "high_risk": True,
    },
    {
        "aliases": ["lithium aluminum hydride", "lialh4", "lah"],
        "cn_name": "氢化铝锂",
        "hazards": ["Reacts violently with water to release flammable gas",
                    "Spontaneously flammable",
                    "Causes severe skin burns"],
        "ghs_codes": ["H260", "H301", "H311", "H314", "H331"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS06"],
        "high_risk": True,
    },
    {
        "aliases": ["sodium borohydride", "nabh4"],
        "cn_name": "硼氢化钠",
        "hazards": ["Flammable solid", "Harmful if swallowed",
                    "Causes severe skin burns"],
        "ghs_codes": ["H228", "H260", "H301", "H311", "H314", "H331"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS06"],
        "high_risk": True,
    },
    {
        "aliases": ["thionyl chloride", "socl2"],
        "cn_name": "亚硫酰氯/氯化亚砜",
        "hazards": ["Highly flammable liquid and vapour",
                    "Causes severe skin burns and eye damage",
                    "Harmful if inhaled"],
        "ghs_codes": ["H225", "H302", "H314", "H332"],
        "signal_word": "Danger",
        "pictograms": ["GHS02", "GHS05", "GHS07"],
        "high_risk": True,
    },
    # ── 生物试剂 ─────────────────────────────────────────────────────────
    {
        "aliases": ["ethidium bromide", "etbr", "ethidium"],
        "cn_name": "溴化乙锭",
        "hazards": ["Harmful if swallowed", "Harmful in contact with skin",
                    "Harmful if inhaled", "Suspected mutagen"],
        "ghs_codes": ["H302", "H312", "H332", "H341"],
        "signal_word": "Warning",
        "pictograms": ["GHS07", "GHS08"],
        "high_risk": True,
    },
    {
        "aliases": ["bromophenol blue", "3',3'',5',5''-tetrabromophenolsulfonphthalein"],
        "cn_name": "溴酚蓝",
        "hazards": ["Causes skin irritation", "Causes eye irritation"],
        "ghs_codes": ["H315", "H319", "H335"],
        "signal_word": "Warning",
        "pictograms": ["GHS07"],
        "high_risk": False,
    },
    # ── 常见无机盐（低危/无危） ────────────────────────────────────────────
    {
        "aliases": ["sodium chloride", "nacl", "salt", "table salt"],
        "cn_name": "氯化钠/食盐",
        "hazards": [],
        "ghs_codes": [],
        "signal_word": "None",
        "pictograms": [],
        "high_risk": False,
    },
    {
        "aliases": ["calcium chloride", "cacl2"],
        "cn_name": "氯化钙",
        "hazards": ["Causes serious eye damage", "Irritating to skin"],
        "ghs_codes": ["H318"],
        "signal_word": "Warning",
        "pictograms": ["GHS05"],
        "high_risk": False,
    },
    {
        "aliases": ["sodium carbonate", "na2co3", "soda ash", "washing soda"],
        "cn_name": "碳酸钠",
        "hazards": ["Causes skin irritation", "Causes serious eye damage",
                    "May cause respiratory irritation"],
        "ghs_codes": ["H315", "H318", "H335"],
        "signal_word": "Warning",
        "pictograms": ["GHS05", "GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["sodium bicarbonate", "nahco3", "baking soda"],
        "cn_name": "碳酸氢钠/小苏打",
        "hazards": [],
        "ghs_codes": [],
        "signal_word": "None",
        "pictograms": [],
        "high_risk": False,
    },
    {
        "aliases": ["potassium chloride", "kcl"],
        "cn_name": "氯化钾",
        "hazards": ["Harmful if swallowed"],
        "ghs_codes": ["H302"],
        "signal_word": "Warning",
        "pictograms": ["GHS07"],
        "high_risk": False,
    },
    {
        "aliases": ["magnesium sulfate", "mgso4", "epsom salt"],
        "cn_name": "硫酸镁",
        "hazards": [],
        "ghs_codes": [],
        "signal_word": "None",
        "pictograms": [],
        "high_risk": False,
    },
    {
        "aliases": ["water", "h2o", "distilled water", "deionized water"],
        "cn_name": "水",
        "hazards": [],
        "ghs_codes": [],
        "signal_word": "None",
        "pictograms": [],
        "high_risk": False,
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# 查询接口
# ─────────────────────────────────────────────────────────────────────────────

def _normalize(s: str) -> str:
    """统一小写并去除多余空白，用于匹配。"""
    return re.sub(r"\s+", " ", s.strip().lower())


def lookup(name: str) -> dict | None:
    """
    在本地数据库中查找化学品。
    支持：完全匹配、包含匹配（name 是别名的子串，或别名是 name 的子串）。
    返回匹配记录字典，未找到返回 None。
    """
    key = _normalize(name)
    # 第一轮：精确别名匹配
    for entry in LOCAL_HAZARD_DB:
        if key in [_normalize(a) for a in entry["aliases"]]:
            return entry
    # 第二轮：前缀/包含匹配（例如 "hydrogen peroxide 30%" → "hydrogen peroxide"）
    for entry in LOCAL_HAZARD_DB:
        for alias in entry["aliases"]:
            norm_alias = _normalize(alias)
            if norm_alias in key or key in norm_alias:
                return entry
    return None


def format_entry(name: str, entry: dict) -> str:
    """将一条记录格式化为可读字符串（供安全检测面板显示）。"""
    lines = [f"【{name}】（{entry['cn_name']}）[本地库]"]
    if entry["signal_word"] and entry["signal_word"] != "None":
        lines.append(f"  信号词：{entry['signal_word']}")
    if entry["ghs_codes"]:
        lines.append(f"  GHS 编码：{', '.join(entry['ghs_codes'])}")
    if entry["pictograms"]:
        lines.append(f"  危险标志：{', '.join(entry['pictograms'])}")
    if entry["hazards"]:
        for h in entry["hazards"]:
            lines.append(f"  ⚠ {h}")
    else:
        lines.append("  ✅ 该物质在本地库中无已知 GHS 危害分类（低危或无危）。")
    return "\n".join(lines)
