from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = PROJECT_DIR / "backend"
JSON_SCHEMA_PATH = PROJECT_DIR / "docs" / "contracts" / "research-v1.schema.json"
TYPESCRIPT_PATH = PROJECT_DIR / "frontend" / "lib" / "api" / "generated" / "research-v1.ts"

sys.path.insert(0, str(BACKEND_DIR))

from app.schemas.research import ResearchOutput, ResultFeedback, RoundChangeSet  # noqa: E402


HEADER = "// Generated by scripts/generate_research_contract.py; do not edit.\n"


def build_json_schema() -> dict[str, Any]:
    schema = ResearchOutput.model_json_schema(by_alias=True, mode="serialization")
    definitions = schema.setdefault("$defs", {})
    for model in (ResultFeedback, RoundChangeSet):
        model_schema = model.model_json_schema(by_alias=True, mode="serialization")
        definitions.update(model_schema.pop("$defs", {}))
        definitions[model.__name__] = model_schema
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://chalk.local/contracts/research-v1.schema.json",
        **schema,
    }


def render_json_schema(schema: dict[str, Any]) -> str:
    return json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _property_name(name: str) -> str:
    if name.isidentifier():
        return name
    return json.dumps(name, ensure_ascii=False)


def _union(parts: list[str]) -> str:
    unique = list(dict.fromkeys(parts))
    return " | ".join(unique) if unique else "never"


def schema_to_typescript(schema: dict[str, Any], indent: int = 0) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return _union([json.dumps(value, ensure_ascii=False) for value in schema["enum"]])
    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return _union([schema_to_typescript(item, indent) for item in schema[union_key]])
    if "allOf" in schema and "properties" not in schema and schema.get("type") != "object":
        return " & ".join(schema_to_typescript(item, indent) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return _union([schema_to_typescript({**schema, "type": item}, indent) for item in schema_type])
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"ReadonlyArray<{schema_to_typescript(schema.get('items', {}), indent)}>"

    properties = schema.get("properties")
    if schema_type == "object" or properties is not None:
        if properties:
            required = set(schema.get("required", []))
            lines = ["{"]
            for name, child in properties.items():
                optional = "" if name in required else "?"
                child_type = schema_to_typescript(child, indent + 1)
                lines.append(
                    f"{'  ' * (indent + 1)}readonly {_property_name(name)}{optional}: {child_type}"
                )
            lines.append(f"{'  ' * indent}}}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Readonly<Record<string, {schema_to_typescript(additional, indent)}>>"
        return "Readonly<Record<string, unknown>>"

    return "unknown"


def render_typescript(schema: dict[str, Any]) -> str:
    definitions = schema.get("$defs", {})
    sections = [HEADER.rstrip("\n")]
    for name in sorted(definitions):
        sections.append(f"export type {name} = {schema_to_typescript(definitions[name])}")
    root_schema = {key: value for key, value in schema.items() if key not in {"$defs", "$id", "$schema"}}
    sections.append(f"export type ResearchOutputBase = {schema_to_typescript(root_schema)}")
    sections.append(
        """export type CandidateHypothesisAt<Id extends CandidateHypothesis[\"id\"]> =
  Omit<CandidateHypothesis, \"id\"> & { readonly id: Id }

export type CandidateHypothesisTuple =
  | readonly [
      CandidateHypothesisAt<\"H1\">,
      CandidateHypothesisAt<\"H2\">,
      CandidateHypothesisAt<\"H3\">,
    ]
  | readonly [
      CandidateHypothesisAt<\"H1\">,
      CandidateHypothesisAt<\"H2\">,
      CandidateHypothesisAt<\"H3\">,
      CandidateHypothesisAt<\"H4\">,
    ]
  | readonly [
      CandidateHypothesisAt<\"H1\">,
      CandidateHypothesisAt<\"H2\">,
      CandidateHypothesisAt<\"H3\">,
      CandidateHypothesisAt<\"H4\">,
      CandidateHypothesisAt<\"H5\">,
    ]

type ResearchOutputCommon = Omit<
  ResearchOutputBase,
  \"profile\" | \"chemistrySubdomain\" | \"chemistry\" | \"hypotheses\"
>

export type ResearchOutput =
  | (ResearchOutputCommon & {
      readonly profile: \"general_science\"
      readonly chemistrySubdomain?: null
      readonly chemistry?: null
      readonly hypotheses: CandidateHypothesisTuple
    })
  | (ResearchOutputCommon & {
      readonly profile: \"chemistry\"
      readonly chemistrySubdomain: string
      readonly chemistry?: ChemistryDetails | null
      readonly hypotheses: CandidateHypothesisTuple
    })"""
    )
    return "\n\n".join(sections) + "\n"


def generated_files() -> dict[Path, str]:
    schema = build_json_schema()
    return {
        JSON_SCHEMA_PATH: render_json_schema(schema),
        TYPESCRIPT_PATH: render_typescript(schema),
    }


def check_generated_files(files: dict[Path, str]) -> int:
    stale = []
    for path, expected in files.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(PROJECT_DIR).as_posix())
    if stale:
        print("Research contract generated files are missing or stale:")
        for path in stale:
            print(f"- {path}")
        print("Run: python scripts/generate_research_contract.py")
        return 1
    print("Research contract generated files are current.")
    return 0


def write_generated_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(PROJECT_DIR).as_posix()}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate research-v1 contract artifacts.")
    parser.add_argument("--check", action="store_true", help="Fail if committed artifacts differ from Pydantic.")
    args = parser.parse_args()
    files = generated_files()
    if args.check:
        return check_generated_files(files)
    write_generated_files(files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
